### ISSUE TITLE
Transactions are broken 

### ISSUE THREAD

**Issue by meatloaf-1** [h4h13/Paisa#507]
Transfers between 2 accounts are non-functional since the last update. Money is neither credited nor debited from either account and the transactions page just shows a blank divider instead of the transfer.
![Screenshot_20240702_123942_Paisa](https://github.com/h4h13/Paisa/assets/112791312/9f775031-a28f-4b57-b65b-f0630c787b91)

**Comment by FosRexx** [comment]
I am having a different kind of issue where the transaction accounts for a transfer is `null`. So, money is neither debited or credited. 
![Screenshot_20240703-153735_Paisa_1_1.png](https://github.com/h4h13/Paisa/assets/105154048/3295672a-c8d2-451b-af43-1a2f00182fce)

**Comment by TheDeadCell** [comment]
I am also experiencing this issue on the current version. On the main paige, it shows blank dividers, and on the accounts page for my default account, it shows a single transaction from null to null.

**Comment by PrestigiousBeat6355** [comment]
Same here

**Comment by ChocolateOverflow** [comment]
1. Old transactions are still shown normally, only new transactions are affected
2. Broken transacntions are not rendered properly on the main page, but are shown with "null to null" on the Accounts page
3. When editing the transaction (from the Accounts page), no category is selected. Selecting categories and saving doesn't fix the issue
4. Expenses work correct, unaffected by the bug

**Comment by validusername19** [comment]
Because of this bug, I have now noticed that transfer type of transactions are overall buggy since version 6.1.1. When you create a new category since this version and set it as transfer category, it's not going to show in the transfer type of transaction, and if you disable the transfer category for this specific category, it's going to show in expense, income and transfer types of transaction. I didn't notice that before because for some reason it works fine with categories that were created before version 6.1.1. Oh, and also this bug will apply to all transfer categories if you import them into an app with version 6.1.1 or higher. Not cool. I can replicate this bug on my Android 9 phone and Android 11 virtual machine. I guess I'm going to stay on version 6.0.8 for as long as possible, even when newer version will be released.

https://github.com/h4h13/Paisa/assets/166646689/7b3fba54-4ef5-434a-b7f9-15430534b789

![Screenshot_20240705_105002](https://github.com/h4h13/Paisa/assets/166646689/58dd19fd-0c2c-4b3d-8d90-caea652af11c)

**Comment by h4h13** [comment]
I have fixed the issue but can't fix the already created ones please check v6.1.7

**Comment by TheDeadCell** [comment]
I just checked v6.1.7, Transfers now appear on the main screen, but do not display the correct category. They also do not transfer money between accounts, all the balances stay the same.

**Comment by validusername19** [comment]
@TheDeadCell same thing for me and it doesn't transfer money as well

![image](https://github.com/h4h13/Paisa/assets/166646689/479cd4bf-db42-44eb-b3a1-5917562b690e)



There is also a bug where it replaces everything with random expenses 👇

https://github.com/h4h13/Paisa/assets/166646689/b6a6537b-74e1-48c8-8202-2d05a9b34864


Sorry that my previous comment was salty, is there a way for me to beta test your application before it's released as stable version? @h4h13

**Comment by PrestigiousBeat6355** [comment]
> I just checked v6.1.7, Transfers now appear on the main screen, but do not display the correct category. They also do not transfer money between accounts, all the balances stay the same.

Same for v6.1.8

**Comment by h4h13** [comment]
Transfer amount should not be calculated neither expense or income as it will become zero so removed calculation 🧮

**Comment by h4h13** [comment]
If I'm doing anything wrong please let me know

**Comment by h4h13** [comment]
> @TheDeadCell same thing for me and it doesn't transfer money as well, the previous bug that I commented was fixed though
> 
> ![image](https://github.com/h4h13/Paisa/assets/166646689/479cd4bf-db42-44eb-b3a1-5917562b690e)
> 
> 
> 
> There is also a bug where it replaces everything with random expenses 👇
> 
> https://github.com/h4h13/Paisa/assets/166646689/b6a6537b-74e1-48c8-8202-2d05a9b34864
> 
> 
> Sorry that my previous comment was salty, is there a way for me to beta test your application before it's released as stable version? @h4h13 

Yes sorry unfortunately I pushed the test code please update to v6.1.8 and remove test accounts and categories

**Comment by PrestigiousBeat6355** [comment]
> If I'm doing anything wrong please let me know 

But it should reflect to account balance, currently account balance remains same after transfer transaction.

**Comment by TheDeadCell** [comment]
As of version 6.2.2, trabsfers now display properly on the home screen and each of the accounts that it applies to. Unfortunately, transfers still do not change the account balance properly (account balances remain the same as before the transfer).

**Comment by ChocolateOverflow** [comment]
Seems to have been fixed after an automatic update.
However, I was just shown a "corrupted, tap to delete" thing in place of the original transaction, with no information on the original, and tapping it just deleted it with no warning/confirmation. Fortunately, I had a record of the corrupted transaction elsewhere and was able to easily remake it.
I would have preferred it either (1) allow me to edit/fix the corrupted transaction or (2) show me its details (and some warning/info) and allow me to recreate the transaction before deleting the corrupted item.

**Comment by h4h13** [comment]
Can't recover currupted transactions so we have to delete and recreate it again

**Comment by h4h13** [comment]
I'm closing this issue for now anything else please raise it as another
